# Generated by Django 5.2.8 on 2025-11-25 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DiaDiem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ten', models.CharField(max_length=200, verbose_name='Tên Địa Điểm')),
                ('loai', models.CharField(choices=[('LS', 'Lịch Sử'), ('VH', 'Văn Hóa'), ('TN', 'Thiên Nhiên')], max_length=2, verbose_name='Phân Loại')),
                ('mo_ta', models.TextField(verbose_name='Mô Tả Chi Tiết')),
                ('hinh_anh_dai_dien', models.ImageField(blank=True, null=True, upload_to='diadiem_images/', verbose_name='Ảnh Đại Diện')),
                ('dia_chi_text', models.CharField(max_length=255, verbose_name='Địa Chỉ (dùng để Geocoding)')),
                ('vido', models.FloatField(blank=True, null=True, verbose_name='Vĩ Độ (Latitude)')),
                ('kinhdo', models.FloatField(blank=True, null=True, verbose_name='Kinh Độ (Longitude)')),
                ('ngay_tao', models.DateTimeField(auto_now_add=True)),
                ('ngay_cap_nhat', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'Địa Điểm',
            },
        ),
    ]
