# Generated by Django 5.2.8 on 2025-11-25 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='diadiem',
            name='dia_chi_text',
        ),
        migrations.AlterField(
            model_name='diadiem',
            name='kinhdo',
            field=models.FloatField(blank=True, help_text='Nhập tọa độ Kinh độ. Ví dụ: 105.8542.', null=True, verbose_name='Kinh Độ (Longitude)'),
        ),
        migrations.AlterField(
            model_name='diadiem',
            name='vido',
            field=models.FloatField(blank=True, help_text='Nhập tọa độ Vĩ độ. Ví dụ: 21.0285.', null=True, verbose_name='Vĩ Độ (Latitude)'),
        ),
    ]
