# Generated by Django 5.2.8 on 2025-11-25 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0002_remove_diadiem_dia_chi_text_alter_diadiem_kinhdo_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='diadiem',
            name='kinhdo',
            field=models.FloatField(blank=True, help_text='Nhập tọa độ Kinh độ (ví dụ: 105.8542).', null=True, verbose_name='Kinh Độ (Longitude)'),
        ),
        migrations.AlterField(
            model_name='diadiem',
            name='vido',
            field=models.FloatField(blank=True, help_text='Nhập tọa độ Vĩ độ (ví dụ: 21.0285).', null=True, verbose_name='Vĩ Độ (Latitude)'),
        ),
    ]
